# Job Statuses
JOB_PENDING = "PENDING"
JOB_RUNNING = "RUNNING"
JOB_COMPLETED = "COMPLETED"
JOB_FAILED = "FAILED"
JOB_PAUSED = "PAUSED"
JOB_STOPPED = "STOPPED"

# Lead Statuses
LEAD_NEW = "NEW_LEAD"
LEAD_CLEANED = "CLEANED"
LEAD_STORED = "STORED"
LEAD_AI_ANALYZED = "AI_ANALYZED"
LEAD_EMAIL_GENERATED = "EMAIL_GENERATED"
LEAD_READY_TO_SEND = "READY_TO_SEND"
LEAD_EMAIL_SENT = "EMAIL_SENT"
LEAD_FOLLOWUP_PENDING = "FOLLOWUP_PENDING"
LEAD_REPLIED = "REPLIED"
LEAD_MEETING_BOOKED = "MEETING_BOOKED"
LEAD_CLOSED = "CLOSED"
LEAD_DO_NOT_CONTACT = "DO_NOT_CONTACT"

# Platforms
PLATFORM_GOOGLE_MAPS = "google_maps"
PLATFORM_GOOGLE_EMAIL = "google_email"
PLATFORM_GOOGLE_SERP = "google_serp"
PLATFORM_SERPER_BULK = "serper_bulk"

# Enrichment statuses
ENRICHMENT_PENDING = "PENDING"
ENRICHMENT_ENRICHED = "ENRICHED"
ENRICHMENT_PARTIAL = "PARTIAL"
ENRICHMENT_FAILED = "FAILED"
ENRICHMENT_SKIPPED_GENERIC_EMAIL = "SKIPPED_GENERIC_EMAIL"
ENRICHMENT_WEBSITE_NOT_FOUND = "WEBSITE_NOT_FOUND"
